---
title: "Question 1 EDA"
author: "Sydney Donati-Leach"
date: "9/27/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(xtable)
library(ggplot2)
library(rms)
library(arm)
library(e1071)
library(caret)
library(pROC)

inc <- read.csv("https://sakai.duke.edu/access/content/group/44141e8f-3928-4af9-a9e8-7feeb029d26f/Datasets/Team%20Project%20Datasets/Team%20Project%201/lalondedata.txt", header = TRUE) 

# Observing the data set
summary(inc)
head(inc)
colnames(inc)

# Dropping the identifier row, as it is not required for our analysis
inc <- inc[,2:ncol(inc)]

# identifying what 0 and 1 means for each factor variable
inc$treat[inc$treat == 0] <- "No Training"
inc$treat[inc$treat == 1] <- "Training"

inc$black[inc$black == 0] <- "Non-Black"
inc$black[inc$black == 1] <- "Black"

inc$hispan[inc$hispan == 0] <- "Non-Hispanic"
inc$hispan[inc$hispan == 1] <- "Hispanic"

inc$married[inc$married == 0] <- "Not Married"
inc$married[inc$married == 1] <- "Married"

inc$nodegree[inc$nodegree == 1] <- "No Degree"
inc$nodegree[inc$nodegree == 0] <- "Degree"

# Converting the categorical variables into factor
inc$treat <- factor(inc$treat)
inc$black <- factor(inc$black)
inc$hispan <- factor(inc$hispan)
inc$married <- factor(inc$married)
inc$nodegree <- factor(inc$nodegree)

# Creating the response variable - comparing re78 against re74
inc$wage_diff <- inc$re78 - inc$re74

# look at revised data set
head(inc)
```

## EDA for Continuous Variables:
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
# wage vs age
ggplot(inc,aes(x=age, y=wage_diff)) +
  geom_point() + geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage Difference by Age",y="Wage Difference",x="Age")
# wage vs educ
ggplot(inc,aes(x=educ, y=wage_diff)) +
  geom_point() + geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage Difference by Education",y="Wage Difference",x="Years of Education")
```
## EDA for Factor Variables:
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
# wage vs treat
ggplot(inc,aes(x=treat, y=wage_diff, fill=treat)) +
  geom_boxplot() + 
  scale_fill_brewer(palette="Blues") +
  labs(title="Wage Difference for Training vs No Training",y="Wage Difference",x="Traning or No Training") +
  theme_classic() + theme(legend.position="none")
# wage vs black
ggplot(inc,aes(x=black, y=wage_diff, fill=black)) +
  geom_boxplot() + 
  scale_fill_brewer(palette="Blues") +
  labs(title="Wage Difference for Black vs Non-Black",y="Wage Difference",x="Black or Non-Black") +
  theme_classic() + theme(legend.position="none")
# wage vs hispanic
ggplot(inc,aes(x=hispan, y=wage_diff, fill=hispan)) +
  geom_boxplot() + 
  scale_fill_brewer(palette="Blues") +
  labs(title="Wage Difference for Hispanic vs Non-Hispanic",y="Wage Difference",x="Hispanic or Non-Hispanic") +
  theme_classic() + theme(legend.position="none")
# wage vs married
ggplot(inc,aes(x=married, y=wage_diff, fill=married)) +
  geom_boxplot() + 
  scale_fill_brewer(palette="Blues") +
  labs(title="Wage Difference for Married vs Not Married",y="Wage Difference",x="Married or Not Married") +
  theme_classic() + theme(legend.position="none")
# wage vs degree
ggplot(inc,aes(x=nodegree, y=wage_diff, fill=nodegree)) +
  geom_boxplot() + 
  scale_fill_brewer(palette="Blues") +
  labs(title="Wage Difference for Degree vs No Degree",y="Wage Difference",x="Degree or No Degree") +
  theme_classic() + theme(legend.position="none")
```

## EDA Age Interactions:
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
# wage vs age by treat
ggplot(inc,aes(x=age, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=treat)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Age by Treatment",y="Wage Difference",x="Age") +
  facet_wrap( ~ treat,ncol= 2) #this is number of "flavors"
# wage vs age by black
ggplot(inc,aes(x=age, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=black)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Age by Black",y="Wage Difference",x="Age") +
  facet_wrap( ~ black,ncol= 2) #this is number of "flavors"
# wage vs age by hispan
ggplot(inc,aes(x=age, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=hispan)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Age by Hispanic",y="Wage Difference",x="Age") +
  facet_wrap( ~ hispan,ncol= 2) #this is number of "flavors"
# wage vs age by married
ggplot(inc,aes(x=age, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=married)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Age by Married",y="Wage Difference",x="Age") +
  facet_wrap( ~ married,ncol= 2) #this is number of "flavors"
# wage vs age by degree
ggplot(inc,aes(x=age, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=nodegree)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Age by Degree",y="Wage Difference",x="Age") +
  facet_wrap( ~ nodegree,ncol= 2) #this is number of "flavors"
```
## EDA Education Interactions:
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
# wage vs educ by treat
ggplot(inc,aes(x=educ, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=treat)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Education by Treatment",y="Wage Difference",x="Education") +
  facet_wrap( ~ treat,ncol= 2) #this is number of "flavors"
# wage vs educ by black
ggplot(inc,aes(x=educ, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=black)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Education by Black",y="Wage Difference",x="Education") +
  facet_wrap( ~ black,ncol= 2) #this is number of "flavors"
# wage vs educ by hispan
ggplot(inc,aes(x=educ, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=hispan)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Education by Hispanic",y="Wage Difference",x="Education") +
  facet_wrap( ~ hispan,ncol= 2) #this is number of "flavors"
# wage vs educ by married
ggplot(inc,aes(x=educ, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=married)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Education by Married",y="Wage Difference",x="Education") +
  facet_wrap( ~ married,ncol= 2) #this is number of "flavors"
# wage vs educ by degree
ggplot(inc,aes(x=educ, y=wage_diff)) +
  geom_point(size = .5, alpha = .7,aes(color=nodegree)) +
  geom_smooth(method="lm",col="red3") + theme_classic() + theme(legend.position="none") +
  labs(title="Wage vs Education by Degree",y="Wage Difference",x="Education") +
  facet_wrap( ~ nodegree,ncol= 2) #this is number of "flavors"
```

